### PR TITLE
Moved artboards to 0,0 coordinates. Added "about" artboard.

### PR DESCRIPTION
**Pull request by jpwain**
Following up @imaaronjames excellent tweaks: 
* Moved the artboards to start at `0,0` coordinate.
* Added an `_About` artboard
* Added a version string for the file (because it varies from the Google release number) to the About artboard.
* Set file version to 1.2, tentatively, calling @imaaronjames update 1.1.
* Added github project URL to the About artboard.

### CODE REVIEW

**Comment by imaaronjames** [comment]
May I suggest 2 changes. 
• Change the _About artboard background color to #fafafa
• Collapse all artboards upon final save

Otherwise, this all looks good.

**Comment by jpwain** [comment]
Good call! Updating now.

**Comment by LPZilva** [comment]
I'll have a look ASAP :+1:

**Comment by LPZilva** [comment]
LGTM :+1:

**Comment by imaaronjames** [comment]
#teamwork!!

**Pull request merged**
